name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./healthbuddy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint black bandit safety -r ./requirements.txt

      - name: Run Pylint
        run: pylint healthbuddy healthbuddy_app

      - name: Run Black
        run: black --check .

      - name: Run Bandit
        run: bandit -r healthbuddy healthbuddy_app

      - name: Check dependencies with Safety
        run: safety check

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./healthbuddy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest -r ./requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: test
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./healthbuddy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Generate deployment package
        run: |
         zip -r deploy.zip . -x "*.git*"
         
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           application_name: ${{ secrets.EB_APPLICATION_NAME }}
           environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
           version_label: "ver-${{ github.sha }}"
           region: ${{ secrets.AWS_REGION }}
           deployment_package: ./healthbuddy/deploy.zip
           existing_bucket_name: elasticbeanstalk-us-east-1-058264363855
           wait_for_environment_recovery: 300         
